config/routes.rb
Nefertiti::Application.routes.draw do
  root :to => 'home#index'

  match 'cv' => 'cv#index', :as => :cv
  match 'contact' => 'contact#index', :as => :contact
  post 'contact/sending' => 'contact#send_contact', :as => :send_contact
  match 'boats' => 'boats#index', :as => :boats
  match 'career' => 'career#index', :as => :career

  match 'boats/engy' => 'boats#engy', :as => :engy
  match 'boats/ezzElKarim' => 'boats#ezz', :as => :ezz
  match 'boats/moustafaElKarim' => 'boats#moustafa', :as => :moustafa
  match 'boats/shroockElKarim' => 'boats#shroock', :as => :shroock
  match 'boats/osa' => 'boats#osa', :as => :osa
  match 'boats/moamenElKarim' => 'boats#moamen', :as => :moamen
  match 'boats/naderElKarim' => 'boats#nader', :as => :nader
  match 'boats/ezzElKarim' => 'boats#ezz', :as => :ezz
  match 'boats/moustafaElKarim' => 'boats#moustafa', :as => :moustafa
  match 'boats/osa' => 'boats#osa', :as => :osa

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/boats_controller.rb
class BoatsController < ApplicationController
	def index
	end

	def engy
	end

	def ezz
	end

	def moustafa
	end

	def shroock
	end

	def osa
	end

	def moamen
	end

	def nader
	end
end

app/controllers/career_controller.rb
class CareerController < ApplicationController
	def index
	end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
	def index 
		@name = params[:name]
		@email = params[:email]
		@message = params[:message]
		@flag = params[:flag]
	end

	def send_contact
		name = params[:n]
		email = params[:e]
		message = params[:m]
		if name == "" || email == "" || message == ""
			redirect_to action: index, name: name, email: email, message: message, flag: true
		else
			UserMailer.generic_email("mohamedtamer92@gmail.com", "Email from #{name}",
		 	"#{name} with email #{email} said:" +"\n" + message).deliver
			redirect_to contact_path
		end
	end
end

app/controllers/cv_controller.rb
class CvController < ApplicationController
	def index
	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boats_helper.rb
module BoatsHelper
end

app/helpers/career_helper.rb
module CareerHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/cv_helper.rb
module CvHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/boats/engy.html.erb
<legend>Engy-K</legend>
<div class="container-fluid">
	<div class="row-fluid">
<div class="span6"><img src="/assets/engy002.jpg"></div>
<div class="span6"><img src="/assets/engy pic 2.jpg"></div>
</div>
</div>
<br>
<p><strong><span style="text-decoration: underline;">* MAIN SPECIFICATION</span></strong></p>
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="343">
<p align="left">Built</p>
</td>
<td valign="top" width="276">
<p align="left">1999</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p align="left">L.O.A (Including Push Bow)</p>
</td>
<td valign="top" width="276">
<p align="left">18.65 M</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p align="left">Beam Over All</p>
</td>
<td valign="top" width="276">
<p align="left">4.37&nbsp;&nbsp; M</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p align="left">Max. Loading Draft</p>
</td>
<td valign="top" width="276">
<p align="left">1.70&nbsp;&nbsp; M</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p align="left">Clear Deck Space</p>
</td>
<td valign="top" width="276">
<p align="left">39.30 M2</p>
</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p><strong><span style="text-decoration: underline;">* Machinery</span></strong></p>
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="343">
<p>Main Engine's   Man 2 × 280 H.P With Total</p>
</td>
<td valign="top" width="276">
<p align="left">560 H.P</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p align="left">Max Running Speed</p>
</td>
<td valign="top" width="276">
<p align="left">11 KTS</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Economic   Speed</p>
</td>
<td valign="top" width="276">
<p align="left">9 KTS</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Main   Engine Generator AC Supply With K.A.V.</p>
</td>
<td valign="top" width="276">
<p align="left">15</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Main   Engine Bilge Pump &amp; Fire Fighting System</p>
</td>
<td valign="top" width="276">
<p align="left">&nbsp;</p>
</td>
</tr>
</tbody>
</table>
<p>&nbsp;</p>
<p><strong><span style="text-decoration: underline;">* Capacities</span></strong></p>
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="343">
<p>Diesel Oil</p>
</td>
<td valign="top" width="276">
<p>9&nbsp;&nbsp;&nbsp; TONS</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Potable Water</p>
</td>
<td valign="top" width="276">
<p>3&nbsp;&nbsp;&nbsp; TONS</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Antipollution   Dispersant Chemicals</p>
</td>
<td valign="top" width="276">
<p align="left">2.2 TONS</p>
</td>
</tr>
</tbody>
</table>
<p><strong><span style="text-decoration: underline;">* Anti Pollution System</span></strong></p>
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="619">
<p>Two Booms Equipped With Adequate   Nozzles To Perform At Least 10 % Of Dispersant Concentration Each Boom Is   Located At One Side Of The Boat Booms Length 5 M Each.</p>
</td>
</tr>
</tbody>
</table>
<p><strong><span style="text-decoration: underline;">* Navigation Equipment</span></strong></p>
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="343">
<p align="left">Magnetic Compass</p>
</td>
<td valign="top" width="276">
<p align="left">&nbsp;</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Radar (24 Miles)</p>
</td>
<td valign="top" width="276">
<p align="left">&nbsp;</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Echo-sounder</p>
</td>
<td valign="top" width="276">
<p align="left">&nbsp;</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>VHF Sail OR</p>
</td>
<td valign="top" width="276">
<p align="left">&nbsp;</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>2 × Search Light (front And Aft)</p>
</td>
<td valign="top" width="276">
<p align="left">&nbsp;</p>
</td>
</tr>
</tbody>
</table>
<p align="left"><strong><span style="text-decoration: underline;">* Safety Equipment</span></strong></p>
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="343">
<p align="left">Life Raft</p>
</td>
<td valign="top" width="276">
<p>15 Persons</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Life Jacket</p>
</td>
<td valign="top" width="276">
<p>25 Units</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Life Buoy</p>
</td>
<td valign="top" width="276">
<p>2&nbsp;&nbsp; Units</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>Fire Fighting System</p>
</td>
<td valign="top" width="276">
<p>&nbsp;</p>
</td>
</tr>
</tbody>
</table>
<p><strong><span style="text-decoration: underline;">* Accommodation </span></strong></p>
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="343">
<p>Seated   Accommodation</p>
</td>
<td valign="top" width="276">
<p>10 Persons</p>
</td>
</tr>
</tbody>
</table>
<p><strong><span style="text-decoration: underline;">* Offered boats crew</span></strong></p>
<table border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="343">
<p align="left">One Certified Bosun</p>
</td>
<td valign="top" width="276">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>One Mechanic Sailor</p>
</td>
<td valign="top" width="276">
<p>&nbsp;</p>
</td>
</tr>
<tr>
<td valign="top" width="343">
<p>One Sailor</p>
</td>
<td valign="top" width="276">
<p>&nbsp;</p>
</td>
</tr>
</tbody>
</table>

app/views/boats/ezz.html.erb
<legend>Ezz El Karim</legend>
<img src="/assets/Ezz-k.jpg">
<h4><strong>1700 BHP Tug Supply Vessel</strong> </h4>
<ul>
	<li>Flag : Egypt</li>
	<li>Built : 2001, Alexandria</li>
	<li>Call Sign : 6 ABS</li>
	<li> Length Overall : 30 m</li>
	<li> Beam : 6.8 in</li>
	<li> Depth : 3.3 m</li>
	<li> M.Draft : 2.4m</li>
	<li> Max Draft : 3.3 m</li>
</ul>
<strong>Capacities</strong>
<ul>
	<li>Diesel Oil : 44 m3</li>
 <li>Fresh Water : 30 m3</li>
  <li>Deck Cargo : 30 Tons</li>
   <li>Deck Area : 95 m2</li>
    <li>Accommodation : 10 Pax</li>
     <li>Seated Accommodation : 20 Pax</li>
      <li>Dispersant Chemicals : 2 Tons</li>
 </ul>      
<strong>Transfer Rates</strong> 
<ul>
<li>Fuel : 45 m3 /hr @ 40M Head</li>
 <li>Fresh Water : 45 m3 / hr @404/1 Head </li>
</ul>
<strong>Machinery</strong>
<ul> 
	<li>Main Engines: 2X GM rated 850 bhp each</li>
	<li> Generators: 2X Perkins 40 kw</li>
	<li> Propellers: Twin Scre convincial with kort nozel</li>
	</ul>
<strong>Performance</strong>
<ul>
 <li>Fuel Consumption: 11 kts@3tons/day or 10 kts@2.2tons/day</li>
 <li>Bollard Pull: 16 tons</li>
 <li> Economic Speed: 10 kts</li>
</ul>
<strong>Deck Equipments</strong>
<ul> 
<li>Tadano Crane S.W.L 2 tons</li>
<li> Winch 5 tons</li>
<li> Pull 2 Stockless Anchors</li> 
</ul>
<strong>Fire Fighting/Safety</strong>
<ul>
	Fire Pump: <br>
	<li> One 360m3 / hr Capacity @ 90 in Head Driven By Deutz Engine & Connected 7b 4 inch Monitor</li>
		<li>One 2- Pump 801713 / hr Capacity @ 45m Head Safety Equipments In Accordance With SOLAS & Flag Requirments</li>
	</ul>
<strong>Navigation / Communications</strong> 
<li>JRC Ruder 48 mile</li><li> Furuno Echo Sounder 300m</li> <li> furuno GPS Navigator</li><li> Magnetic Compass</li><li> 2 X Icom VHF S.S.B</li> <li> 2 X VHF Hand Help</li> 

app/views/boats/index.html.erb
<legend>Boats</legend>
<div class="well well-small span5"><img style="display: block; margin-left: auto; margin-right: auto;" src="/assets/osa_small.jpg">
	<br>
	<p style="text-align: center"><%= link_to "Osa Viscount-K", osa_path%>
	<br>
	8160 BHP
	</p>
</div>
<div class="well well-small span5"><img style="display: block; margin-left: auto; margin-right: auto; height: 120px;" src="/assets/ezz_small.gif">
	<br>
	<p style="text-align: center"><%= link_to "Ezz el karim", ezz_path%>
	<br>
	1700 BHP</p>
</div>
<div class="well well-small span5"><img style="display: block; margin-left: auto; margin-right: auto; height: 120px;" src="/assets/moustafa_small.jpg">
	<br>
	<p style="text-align: center"><%= link_to "Moustafa El Karim", moustafa_path%>
	<br>
	460 BHP
	</p>
</div>
<div class="well well-small span5"><img style="display: block; margin-left: auto; margin-right: auto;" src="/assets/shroock_small.jpg">
	<br>
	<p style="text-align: center"><%= link_to "Shroock El Karim", shroock_path%>
	<br>
	1500 BHP</p>
</div>
<div class="well well-small span5"><img style="display: block; margin-left: auto; margin-right: auto;" src="/assets/engy_small.jpg">
	<br>
	<p style="text-align: center"><%= link_to "Engy-K", engy_path%>
	<br>
	560 BHP
	</p>
</div>
<div class="well well-small span5"><img style="display: block; margin-left: auto; margin-right: auto; height: 120px;" src="/assets/Moamen_small.jpg">
	<br>
	<p style="text-align: center"><%= link_to "Moamen El Karim", moamen_path%>
	<br>
	1040 BHP
	</p>
</div>
<div class="well well-small span5"><img style="display: block; margin-left: auto; margin-right: auto; height: 120px;" src="/assets/Nader.jpg">
	<br>
	<p style="text-align: center"><%= link_to "Nader El Karim", nader_path%>
	<br>
	2250 BHP</p>
</div>
<audio id="music" class="pull-right" autoplay>
  <source src="/assets/boats.ogg" type="audio/ogg">
  Your browser does not support the audio tag.
</audio>

app/views/boats/moamen.html.erb
<legend>Moamen El Karim</legend>
<div><p align="center"><img src="/assets/Moamen.jpg"></p>
	<br>
<p style="text-align: left;" dir="ltr"><strong>*<span style="text-decoration: underline;">PARTICULAR</span></strong></p>
<table style="width: 387px; text-align: left;" dir="rtl" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td dir="ltr" width="149">
<p>Egypt</p>
</td>
<td width="238">
<p dir="ltr">Flag</p>
</td>
</tr>
<tr>
<td width="149">
<p dir="ltr">2004 Alexandria</p>
</td>
<td width="238">
<p dir="ltr">Built</p>
</td>
</tr>
<tr>
<td width="149">
<p dir="ltr">19 m</p>
</td>
<td width="238">
<p dir="ltr">Length   Overall</p>
</td>
</tr>
<tr>
<td width="149">
<p dir="ltr">5.5 m</p>
</td>
<td width="238">
<p dir="ltr">Beam</p>
</td>
</tr>
<tr>
<td width="149">
<p dir="ltr">1.8 m</p>
</td>
<td width="238">
<p dir="ltr">Depth</p>
</td>
</tr>
<tr>
<td width="149">
<p dir="ltr">2.2 m</p>
</td>
<td width="238">
<p dir="ltr">Draft</p>
</td>
</tr>
</tbody>
</table>
<table style="width: 634px; text-align: left;" dir="rtl" border="1" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td width="406">
<p dir="ltr">20 m3</p>
</td>
<td width="228">
<p dir="ltr">Diesel Oil</p>
</td>
</tr>
<tr>
<td width="406">
<p dir="ltr">7&nbsp; m3</p>
</td>
<td width="228">
<p dir="ltr">Fresh Water</p>
</td>
</tr>
<tr>
<td width="406">
<p dir="ltr">10 Tons</p>
</td>
<td width="228">
<p dir="ltr">Deck Cargo</p>
</td>
</tr>
<tr>
<td width="406">
<p dir="ltr">50 m2</p>
</td>
<td width="228">
<p dir="ltr">Deck Area</p>
</td>
</tr>
<tr>
<td width="406">
<p dir="ltr">10 Pax</p>
</td>
<td width="228">
<p dir="ltr">Accommodation</p>
</td>
</tr>
<tr>
<td valign="top" width="406">
<p dir="ltr">30 Pax</p>
</td>
<td valign="top" width="228">
<p dir="ltr">Seated Accommodation</p>
</td>
</tr>
<tr>
<td valign="top" width="406">
<p dir="ltr">2 Tons</p>
</td>
<td valign="top" width="228">
<p dir="ltr">Dispersant   chemicals</p>
</td>
</tr>
</tbody>
</table>
<p style="text-align: left;">&nbsp;</p>
<p style="text-align: left;"><strong>*<span style="text-decoration: underline;">Transfer Rates</span></strong></p>
<table style="width: 647px; text-align: left;" dir="rtl" border="1" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td width="491">
<p dir="ltr">8 m 3 / hr @ 10 m   head</p>
</td>
<td width="131">
<p dir="ltr">Fuel</p>
</td>
<td width="25">
<p dir="ltr">&nbsp;</p>
</td>
</tr>
</tbody>
</table>
<br>
<p style="text-align: left;"><strong>*<span style="text-decoration: underline;">Machinery</span></strong></p>
<table style="width: 645px; text-align: left;" dir="rtl" border="0" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td valign="top" width="489">
<p dir="ltr">2   ×Cat 520 HP each</p>
</td>
<td width="156">
<p dir="ltr">Main   Engines</p>
</td>
</tr>
<tr>
<td valign="top" width="489">
<p dir="ltr">Perkins   20 KW</p>
</td>
<td width="156">
<p dir="ltr">Generators</p>
</td>
</tr>
<tr>
<td valign="top" width="489">
<p dir="ltr">Twin   Screw Conventional</p>
</td>
<td width="156">
<p dir="ltr">Propellers</p>
</td>
</tr>
</tbody>
</table>
<br>
<p style="text-align: left;"><strong>*<span style="text-decoration: underline;">Performance </span></strong></p>
<table style="width: 648px; text-align: left;" dir="rtl" border="1" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td width="429">
<p dir="ltr">2.5 Tons / Day @   11 Kts</p>
</td>
<td width="219">
<p dir="ltr">Fuel Consumption</p>
</td>
</tr>
<tr>
<td width="429">
<p dir="ltr">2.2 Tons / Day @ 11 Kts</p>
</td>
<td width="219">
<p dir="ltr">&nbsp;</p>
</td>
</tr>
<tr>
<td width="429">
<p dir="ltr">14 Tons</p>
</td>
<td width="219">
<p dir="ltr">Bollard   Pull</p>
</td>
</tr>
<tr>
<td width="429">
<p dir="ltr">10 Kts</p>
</td>
<td width="219">
<p dir="ltr">Economic   Speed</p>
</td>
</tr>
</tbody>
</table>
<br>
<p style="text-align: left;"><strong>*<span style="text-decoration: underline;">Navigation / Communication</span></strong></p>
<table style="width: 335px; text-align: left;" dir="rtl" border="1" cellspacing="0" cellpadding="0">
<tbody>
<tr>
<td width="335">
<p dir="ltr">JRC Radar 24   mile</p>
</td>
</tr>
<tr>
<td width="335">
<p dir="ltr">Navman Echo   Sounder 300 m</p>
</td>
</tr>
<tr>
<td width="335">
<p dir="ltr">Furuno GPS   Navigator</p>
</td>
</tr>
<tr>
<td width="335">
<p>Magnetic Compass</p>
</td>
</tr>
<tr>
<td width="335">
<p dir="ltr">JRC VHF S.S.B</p>
</td>
</tr>
</tbody>
</table>
<br>
<p>Safety Equipments In Accordance To SOLAS &amp; Flag Requirements.</p>
<p align="center"><img src="/assets/Moamen2.jpg"></p></div>

app/views/boats/moustafa.html.erb
<legend>Moustafa El Karim</legend>
<p align="center"><img src="/assets/moustafa pic2.jpg"></p>
<br><br>
<strong>CAPACITIES</strong>
<ul>
<li>FUEL OIL: 10 Tons </li>
<li>POTABLE WATER: 4 Tons</li>
<li>ANTI POLLUTION DISPERSANT CHEMICALS: 2 Tons</li>
</ul>
<strong>ANTI POLLUTION SYSTEM</strong>
<ul> TWO BOOMS EQUIPPED WITH ADEQUATE NOZZLES TO PERFORM AT LEAST 10% OF DISPERSANT CONCENTRATION EACH BOOM IS LOCATED AT ONE SIDE OF THE BOAT BOOMS LENGTH 6 M EACH. LENGTH OF SPRAY PAR 4 M EACH. </ul>
<strong>NAVIGATION EQUIPMENT</strong>
<ul>
	<li>MAGNETIC COMPASS.</li>
	<li>COMPASS.</li>
	<li>RADAR ( 24 MILLES ).</li>
	<li>ECHSOUNDER.</li>
	<li>VHF SAILOR.</li>
	<li>2 X SEARCH LICHT ( FRONT AND AFT)</li>
	<li>GPS.</li>
	</ul>
	<strong>SAFETY EQUIPMENT</strong>
	<ul>
		<li>LIFE RAFT: 15 PERSONS</li>
		<li>LIFEJACKET: 25 UNITS</li>
		<li>LIFE BOUY: 2 UNITS</li>
		<li>FIRE FITTING SYSTEM.</li> 
</ul>
<strong>ACCOMODATION</strong>
<ul>SEATED ACCOMODATION: 15 PERSONS</ul>
<strong>OFFERED BOATS CREW</strong>
<ul>
<li>ONE CERTIFIED BOSUN.</li>
<li>ONE MECHANIC SAILOR.</li>
<li>TWO SAILORS</li>
</ul>

app/views/boats/nader.html.erb
<legend>Nader El Karim</legend>
<div class="container-fluid">
	<div class="row-fluid">
		<div class="span6">
			<img src="/assets/Nader2.jpg">
		</div>
		<div class="span6">
			<img src="/assets/Nader3.jpg">
		</div>
	</div>
</div>
<div>
	<br>
<div class="HeadCell2">Main particulars</div>
<ul class="SubMenu">
<li>2250 B.H.P</li>
<li>L.O.A 35M </li>
<li>Breadth 7.5m </li>
<li>Built 2011</li>
<li>Max draft 2.5m </li>
<li>Clear deck space 120 m² </li>
<li>Deck cargo 52 tons </li>
<li>Speed 10 – 15 Kts </li>
<li>Tank capacity :  			<br> - 100 tons Diesel  			<br> - 60  tons fresh water </li>
</ul>
<br><br style="height: 10px; line-height: 10px;">
<div class="HeadCell2">Communications</div>
<br style="height: 10px; line-height: 10px;"> 
<ul class="SubMenu">
<li>2 fixed V.H.F radio </li>
<li>3 potable V.H.F radio (walky talky ) </li>
<li>2 GPS chart plotter </li>
<li>Radar </li>
<li>Echo sounder </li>
<li>Magnetic compass </li>
<li>A.I.S</li>
</ul>
<br><br style="height: 10px; line-height: 10px;">
<div class="HeadCell2">Machinery &amp; propulsion</div>
<br style="height: 10px; line-height: 10px;"> 
<ul class="SubMenu">
<li>Main engine: " 3 GM Detroit diesel 750 Bhp per each" </li>
<li>Triple screw</li>
<li>2 Generators </li>
<li>Fire fighting pump </li>
<li>Fuel transfer pump </li>
<li>Water transfer pump </li>
<li>Side crane 3 tons </li>
<li>A.H windlass winch </li>
</ul>
<br><br style="height: 10px; line-height: 10px;">
<div class="HeadCell2">Accommodation</div>
<br style="height: 10px; line-height: 10px;"> 
<ul class="SubMenu">
<li>60 seated persons</li>
<li>Boat is fully Air conditioned </li>
<li>Kitchen &amp; Dining room </li>
<li>3 Bath rooms</li>
<li>T.V LCD with DVD reader &amp; surround system</li>
</ul>
</div>

app/views/contact/index.html.erb
<!-- <audio id="music" class="pull-right" autoplay>
  <source src="/assets/seagull.ogg" type="audio/ogg">
  Your browser does not support the audio tag.
</audio> -->
<legend>Contact us</legend>
<div class="span12">
        <strong>Administration hierarchy:</strong>
        <img src="/assets/nefertiti.png">
</div>
      <br>
<div class="container-fluid">
  <div class="row-fluid">
    <div class="span6">
      <br>
    	<strong>Address:</strong> 6, EL NASR ST., EL GOMROUK, ALEX, EGYPT 	<br> <strong>Phone:</strong> +2 03- 4840127 – 4813726<br> <strong>Fax:</strong> +2 03- 4878399	<br><strong>E-mail: </strong><a href="mailto:nefertitimarine@hotmail.com">nefertitimarine@hotmail.com</a>
      <hr>
    	<div>
        <%if @flag == "true"%>
        <p style="color:red;">You did not enter all the fields</p>
        <%end%>
<%= form_tag("#{send_contact_path}", :method => "post") do %>
  <%= label_tag(:i1, "Name:") %>
  <%= text_field_tag(:n, "#{@name}") %>
  <%= label_tag(:i2, "Email:") %>
  <%= email_field_tag(:e, "#{@email}") %>
  <%= label_tag(:i3, "Message:") %>
  <%= text_area_tag "m", "#{@message}", :size=>"10x10" %>
  <br>
  <p style="color:red;">All fields above are required</p>
  <%= submit_tag "Send", class: "btn btn-success btn-large"%>
<% end %>
</div>
    </div>
    <div class="span6">
      <br>
<iframe width="425" height="350" frameborder="0" scrolling="no" marginheight="0" marginwidth="0" src="https://maps.google.com.eg/maps?near=%D8%A7%D9%84%D8%AC%D9%85%D8%B1%D9%83,+%D8%B1%D8%A3%D8%B3+%D8%A7%D9%84%D8%AA%D9%8A%D9%86%D8%8C+%D9%82%D8%B3%D9%85+%D8%A7%D9%84%D8%AC%D9%85%D8%B1%D9%83%D8%8C+%D8%A7%D9%84%D8%A3%D8%B3%D9%83%D9%86%D8%AF%D8%B1%D9%8A%D8%A9&amp;geocode=CSEbHF2RIBRaFRc83AEdVPbHASkHVu77_cP1FDHg3U3NDu-yCA&amp;q=nefertiti+marine&amp;f=l&amp;dq=El+Gomrok,+Ras+at+Tin,+Qesm+Al+Gomrok,+Alexandria+Governorate&amp;sll=31.210518,29.88194&amp;sspn=0.019086,0.032015&amp;ie=UTF8&amp;hq=nefertiti+marine&amp;hnear=&amp;t=m&amp;cid=3079526335749487360&amp;ll=31.265309,30.008876&amp;spn=0.00642,0.00912&amp;z=16&amp;output=embed"></iframe><br /><small><a class="pull-right" href="https://maps.google.com.eg/maps?near=%D8%A7%D9%84%D8%AC%D9%85%D8%B1%D9%83,+%D8%B1%D8%A3%D8%B3+%D8%A7%D9%84%D8%AA%D9%8A%D9%86%D8%8C+%D9%82%D8%B3%D9%85+%D8%A7%D9%84%D8%AC%D9%85%D8%B1%D9%83%D8%8C+%D8%A7%D9%84%D8%A3%D8%B3%D9%83%D9%86%D8%AF%D8%B1%D9%8A%D8%A9&amp;geocode=CSEbHF2RIBRaFRc83AEdVPbHASkHVu77_cP1FDHg3U3NDu-yCA&amp;q=nefertiti+marine&amp;f=l&amp;dq=El+Gomrok,+Ras+at+Tin,+Qesm+Al+Gomrok,+Alexandria+Governorate&amp;sll=31.210518,29.88194&amp;sspn=0.019086,0.032015&amp;ie=UTF8&amp;hq=nefertiti+marine&amp;hnear=&amp;t=m&amp;cid=3079526335749487360&amp;ll=31.265309,30.008876&amp;spn=0.00642,0.00912&amp;z=16&amp;source=embed" style="color:#0000FF;text-align:right">Show bigger map</a></small></div></div></div>